### ISSUE TITLE
Kind of confused with the computing result.

### ISSUE THREAD

**Issue by ghost** [CIDARLAB/Cello-v3-Core#9]
I noticed that in the assets folder there's one presentation file, and in the slide 7 with the result shown. I'm trying to reproduce the result here to facilitate the understanding.

I use the exactly same input, `g77_boolean.v` and SC1C1G1T1 as the UCF.  From the result:
```
('out84', 4) output YFP_reporter 4 with c: 1.0 and outscore=5.047655330767436
('out81', 5) output RFP_reporter 5 with c: 1.0 and outscore=0.0021151583018559736
```

which is different from the result shown in the slide. The image is from the slide.
<img width="908" alt="image6" src="https://github.com/CIDARLAB/Cello-v3-Core/assets/44153667/195fa0d4-f58b-4f1d-9b55-2b3b4a43cfe8">

Apart from this, my reported circuit score is 97.73156629476492. Also the reported YFP reporter and RFP reporter score is slightly different as well.

Please refer to the commits in this [repo](https://github.com/gustavoquincy/Cello-v3-Core) to look into the result generation process.

I wonder if the difference is due to the randomizations in the package.

**Comment by chris-krenz** [comment]
I've been developing Cello on a separate fork and have previously been in communication with the person responsible for the early development of this version of Cello. 

I believe the reason for the discrepancy you identified is that the scores in the presentation are the *log* of the ratio of the 'lowest high'/'highest low'.  The current version of the program actually does not take the log; it is just the ratio.  I believe this decision was explicit/intentional, though I'm not entirely clear on the motivation; I will try to clarify this. (Also, I believe the score of ~97 that you reference is actually the 'worst' score.)

Note, we will be updating this repo in the near future, and a number of things will change.  While the version of the repo you are using actually does not have any stochastic processes, the newer version will use dual annealing (similar to Cello 2.0) to find a solution.  (This is vastly more time efficient, and it does find a good result, though unless an exhaustive search is done, a global optimum cannot be guaranteed.)  So if you rerun this test in the new version, you will notice some variations, unless you explicitly set the 'exhaustive' option.  I also hope you'll find the newer formatting of the output a bit more clear.

Thank you for the post.  I'll try to update the contents of the assets folder to more closely reflect the current state/functionality of the program.

**Comment by ginomcfino** [comment]
Can you guys please close the issue? 

The code and output is correct as described -- the screenshot was from an earlier work-in-progress.

This 'issue' has been sitting here for months...

If you guys need any assistance, lmk

**Comment by ginomcfino** [comment]
Can you guys please close the issue?

The code and output is correct as described -- the screenshot was from an earlier work-in-progress.

This thing shouldn't be sitting here for months...

BTW, if you guys need any assistance, lmk

**Comment by ginomcfino** [comment]
Can you guys please close the issue?

The code and output was correct as described, and the screenshot as pointed out is from an even earlier work-in-progress. Note that in the early versions you referred to, there was no randomization in the computing outputs.

BTW, if you guys need anything, I'm happy to help
